name: Playstore deployment
on:
  push:
    branches:
      - master
jobs:
  #CI
  build_android:
    name: Building Android 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_secrets.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.13.6
      - name: Install Flutter dependencies
        run: flutter pub get
        # Add build runner commands here if you have any

        
      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

          
      - name: Build the Bundle
        run: flutter build appbundle --release
      - name: Upload artifact to Github
        uses: actions/upload-artifact@v1
        with:
          name: release-Bundle
          path: build/app/outputs/bundle/release/app-release.aab
          

      - name: Create Google Play Config file
        run : |
          echo "$PLAY_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
        env:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}

      - name: Distribute app to Beta track 🚀
        run: bundle exec fastlane beta

  #CD
  deploy_android:
    name: Deploying to playstore
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_secrets.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.13.6
      - run: flutter pub get
      - run: flutter build appbundle --release
      - name: Upload artifact to Github
        uses: actions/upload-artifact@v1
        with:
          name: release-Bundle
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Deploy to Play Store (BETA)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
         serviceAccountJson: absher-400309-317f93cdd5f7.json
         packageName: com.AbsherApp.HomeServices
         releaseFile: build/app/outputs/bundle/release/app-release.aab
                      
         track: alpha
         whatsNewDirectory: whatsnew/
